- name: Install vscode, aws-cli and intellij
  pacman: name={{item}} state=present
  with_items:
      - code
      - aws-cli
      - dbeaver
      - intellij-idea-community-edition
  become: yes

# Install using snap
- name: Install dbeaver, postman and STS
  yay: name={{item}} state=present
  with_items:
    - postman 
    - spring-tool-suite   
  become: yes

- name: Install infracost
  shell: |
    curl --silent --location "https://github.com/infracost/infracost/releases/latest/download/infracost-$(uname -s)-amd64.tar.gz" | tar xz -C /tmp
    mv /tmp/infracost-$(uname -s | tr '[:upper:]' '[:lower:]')-amd64 /usr/local/bin/infracost
  become: yes

- name: Install MongoBooster
  shell: |
    curl --silent --location https://s3.mongobooster.com/download/releasesv6/nosqlbooster4mongo-6.1.6.AppImage
    mv nosqlbooster4mongo-6.1.6.AppImage /usr/local/bin/nosqlbooster4mongo-6.1.6.AppImage
  become: yes
