- name: Install vscode and variety
  apt: name={{item}} state=present
  with_items:
      - code
      - variety
  become: yes

# Install using snap
- name: Install dbeaver, terraform, postman and spotify
  snap: name={{item}} state=present
  with_items:
    - dbeaver-ce
    - terraform
    - postman
    - spotify
  become: yes

- name: Install intellij
  snap: 
    name: intellij-idea-community
    classic: yes
  become: yes

- name: Install slack
  snap: 
    name: slack
    classic: yes
  become: yes

- name: Install skype
  snap: 
    name: skype
    classic: yes
  become: yes

- name: Install STS
  shell: |
    mkdir  /opt/springsource
    wget https://download.springsource.com/release/STS4/4.5.0.RELEASE/dist/e4.14/spring-tool-suite-4-4.5.0.RELEASE-e4.14.0-linux.gtk.x86_64.tar.gz -O STS.tar.gz
    mv STS.tar.gz /opt/springsource
    cd /opt/springsource/
    tar -xzf STS.tar.gz 
    echo "[Desktop Entry]
      Encoding=UTF-8
      Name=Spring IDE
      Comment=Spring IDE
      Exec=/opt/springsource/sts-4.5.0.RELEASE/SpringToolSuite4
      Icon=/opt/springsource/sts-4.5.0.RELEASE/icon.xpm
      Terminal=false
      Type=Application
      Categories=GNOME;Application;Development;Programming;IDE;
      Keywords=Java,Eclipse,Spring,IDE,Development
      StartupNotify=true" >  /usr/share/applications/STS.desktop
    rm STS.tar.gz 
  become: yes

