- name: Playbook to install dotfiles (https://github.com/krismorte/dotfiles.git)
  hosts: localhost
  tasks:
    - include: tasks/mint/repositories.yml
    - include: tasks/mint/system.yml
    - include: tasks/mint/languages.yml
    - include: tasks/mint/tools.yml
    - include: tasks/mint/applications.yml
