- name: Playbook to install dotfiles (https://github.com/krismorte/dotfiles.git)
  hosts: localhost
  tasks:
    - import_tasks: tasks/mac/system.yml 
    - import_tasks: tasks/mac/languages.yml 
    - import_tasks: tasks/mac/tools.yml 
    - import_tasks: tasks/mac/applications.yml
