# Config terraform repository
- name: TUpdate apt
  shell: |
    apt update
  check_mode: yes
  become: yes

- name: Install languages
  apt: name={{item}} state=present
  with_items:
      - openjdk-8-jdk      
      - nodejs
      - terraform
      - packer
      # - python3-pip #aws prerequisite
      # - golang-go
  become: yes


  



