- name: Finxing keys
  shell: |
    pacman -Sy archlinux-keyring 
    pacman -Syyu
  become: yes

- name: Install list of packages
  apt: name={{item}} state=present
  with_items:
      - build-essential
      - curl
      - docker-compose
      - docker.io
      - make
      - wget
      - openvpn
      - snapd
      - apt-transport-https
      - virtualbox-6.0
  become: yes


