- name: Install list of packages
  apt: name={{item}} state=present
  with_items:
      - build-essential
      - curl
      - docker-compose
      - docker
      - docker.io
      - make
      - wget
      - openvpn
      - snapd
      - apt-transport-https
      - virtualbox
  become: yes


