- name: Install list of packages
  apt: name={{item}} state=present
  with_items:
      - curl
      - docker-compose
      - docker
      - docker.io
      - wget
      - openvpn
      - snapd
      - apt-transport-https
      - gnupg # needed for terraform
      - software-properties-common # needed for terraform
      - lsb-release # needed for trivy
  become: yes


